on:
  workflow_call:

jobs:
  Release-490_to_Release-500:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: Release-5.0.0
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo Number of commits to fetch. 0 indicates all history for all branches and tags.Default: 1.
    - run: echo "🤖 The ${{ github.repository }} repository has been cloned to the runner."
    - run: |
        git config --local user.email "mkim@it.ucla.edu"
        git config --local user.name "[github action]"
        git merge origin/Release-4.9.0 -s ort -Xours
        git push origin Release-5.0.0
    - run: echo "Branch was auto-merged into another branch using Github Actions"
