name: Branch Merge Workflow

on:
  push:
    branches:  [ vars.BRANCH1 ]
    paths:
      '**' # should be same as not having a paths filter but want to make explicit
  pull_request:
    branches: [ vars.BRANCH1 ]
    paths:
      '**' # should be same as not having a paths filter but want to make explicit
  
jobs:
  Branch470_Branch500:
    if: ${{ github.ref == 'refs/heads/vars.BRANCH1' }} # The fully-formed ref of the branch or tag that triggered the workflow run (GA contexts)
    uses: ./.github/workflows/reusable_branch_merge.yml
    with:
      first_branch: ${{ vars.BRANCH1 }}
      next_branch: ${{ vars.BRANCH2 }}
