name: Branch Merge Workflow

on:
  push:
    branches:  [ Release-4.7.0 , Release-4.9.0 ]
    paths:
      '**' # should be same as not having a paths filter but want to make explicit
  pull_request:
    branches: [ Release-4.7.0 , Release-4.9.0 ]
    paths:
      '**' # should be same as not having a paths filter but want to make explicit
  
jobs:
  Release-470_first:
    if: github.ref == 'refs/heads/Release-4.7.0' # The fully-formed ref of the branch or tag that triggered the workflow run (GA contexts)
    uses: ./.github/workflows/4.7.0_to_4.9.0.yml
  Release-470_second:
    if: github.ref == 'refs/heads/Release-4.7.0' # The fully-formed ref of the branch or tag that triggered the workflow run (GA contexts)
    needs: Release-470_first # conditioned upon previous job (merge) completing, that way third has all changes from first as well
    uses: ./.github/workflows/4.9.0_to_5.0.0.yml
    
  Release-490:
    if: github.ref == 'refs/heads/Release-4.9.0' # The fully-formed ref of the branch or tag that triggered the workflow run (GA contexts)
    uses: ./.github/workflows/4.9.0_to_5.0.0.yml
