name: Branch Merge Workflow

on:
  push:
    branches:  [ R470 ]
    paths:
      '**' # should be same as not having a paths filter but want to make explicit
  pull_request:
    branches: [ R470 ]
    paths:
      '**' # should be same as not having a paths filter but want to make explicit
  
jobs:
  R470_R500:
    if: ${{ github.ref == 'refs/heads/R470' }} # The fully-formed ref of the branch or tag that triggered the workflow run (GA contexts)
    uses: ./.github/workflows/reusable_branch_merge.yml
    with:
      first_branch: R470
      second_branch: R500
